spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: c51aeb1d29efb0a9cf90
            client-secret: ebbde38b79bd9fbf5d99f8582782babc32ffa20f
          google:
            client-id: 72933397707-f0hgvb308df3gi6drgk649o1pvvt1f0s.apps.googleusercontent.com
            client-secret: T03RneVD5gQ9xsvPocS0zG5j
          facebook:
            client-id: 860906551058973
            client-secret: 38bf088e4846195ab831551a4424b325